dist: bionic
matrix:
  include:
    - language: bash
      install:
        - ./bash/test/shunit2Install.sh
        - sudo apt-get install -y softhsm2
      script:
        - ./bash/test/softHSMTest.sh
    - language: node_js
      node_js:
        - "12"
      install:
        - export nodejsInstall="curl --silent --show-error https://raw.githubusercontent.com/davidkhala/node-utils/master/install.sh"
        - sudo apt-get install -y softhsm2
        - $nodejsInstall | bash -s nodeGYPDependencies
        - npm config set package-lock false
        - ./install.sh fabricInstall -d
        - npm install --global lerna
        - cd nodejs; npm install; lerna bootstrap --no-ci; cd -
      script:
        - cd nodejs; npm test; cd -



