matrix:
  include:
    - language: node_js
      node_js:
        - "10"
      dist: bionic
      cache:
        directories:
          - nodejs/node_modules
      install:
        - export nodejsInstall="curl --silent --show-error https://raw.githubusercontent.com/davidkhala/node-utils/master/install.sh"
        - $nodejsInstall | bash -s nodeGYPDependencies
        - curl --silent --show-error https://raw.githubusercontent.com/davidkhala/node-utils/master/scripts/npm.sh | bash -s packageLock false
        - ./install.sh fabricInstall
        - npm install --global lerna
        - cd nodejs; lerna bootstrap; cd -;
      script:
        - node nodejs/test



