matrix:
  include:
    - language: node_js
      node_js:
        - "12"
      dist: bionic
      install:
        - export nodejsInstall="curl --silent --show-error https://raw.githubusercontent.com/davidkhala/node-utils/master/install.sh"
        - $nodejsInstall | bash -s nodeGYPDependencies
        - npm config set package-lock false
        - ./install.sh fabricInstall -d
        - npm install --global lerna
        - cd nodejs; npm install; cd -
        - lerna bootstrap --no-ci
        - ./bash/test/shunit2Install.sh
      script:
        - cd nodejs;
        - npm test
        - ./bash/test/softHSMTest.sh



