# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on:  push

jobs:

  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-node@main
      with:
        check-latest: true
        node-version: lts/*
    - run: ./install.sh fabricInstall -d -s
    - run: npm install
      working-directory: nodejs
    - run: npm test
      working-directory: nodejs
      env:
        binPath: ${{ github.workspace }}/bin/
